name: Build ISO

on:
  workflow_dispatch:
    inputs:
      ubuntu-version:
        description: 'Ubuntu version to build'
        type: choice
        required: true
        default: 'focal'
        options: ['focal', 'jammy']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.8
          check-latest: true
      
      - name: Setting up Jinja2
        run: |
          pip install jinja2
          
      - name: Render Jinja template
        env:
          JINJA_CONFIG: ${{ secrets.JINJA_CONFIG }}
        run: python render.py
        
      - name: Build ISO
        uses: addnab/docker-run-action@v3
        with:
          image: deserializeme/pxeless
          options: -v ${{ github.workspace }}:/data
          run: -a -u user-data -e -n ${{ github.event.inputs.ubuntu-version }} -r
      
      - name: Rename ISO
        run: mv ubuntu-autoinstall.iso ubuntu-autoinstall-${{ github.event.inputs.ubuntu-version }}.iso
      
      - name: Upload the custom image
        uses: actions/upload-artifact@v3
        with:
          name: Autoinstall ISO
          path: ubuntu-autoinstall-${{ github.event.inputs.ubuntu-version }}.iso
